#!/usr/bin/env bash

# (C) 2026 Takayuki Sato
# MIT License
# https://github.com/sttk/go-fav

readonly ORIG_GOTOOLCHAIN=$(go version | cut -f 3 -d' ')

opts=""

for v in "$@"
do
  if [[ $v == '-'* ]]
  then
    opts="${opts} $v"
    continue
  fi

  go env -w GOTOOLCHAIN="go$v"
  go version
  go clean -cache -testcache
  go test $opts -cover $(go list ./... | grep -v /benchmark)
  exitcd=$?
  echo ""
  if [[ ${exitcd} -gt 0 ]]; then
    read -p "Continue? (Y/n) " userinput
    if [ "$(echo ${userinput} | tr '[:upper:]' '[:lower:]')" == "n" ]; then
      break
    fi
  fi
done

if [[ "$ORIG_GOTOOLCHAIN" != "" ]]; then
  go env -w GOTOOLCHAIN="$ORIG_GOTOOLCHAIN"
fi
